<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="5" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-24T15:05:21Z" name="Default suite" finished-at="2024-02-24T15:06:02Z" duration-ms="41816">
    <groups>
    </groups>
    <test started-at="2024-02-24T15:05:21Z" name="Default test" finished-at="2024-02-24T15:06:02Z" duration-ms="41816">
      <class name="testnextsp.updateProductTest">
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:testnextsp.updateProductTest@2145b572]" started-at="2024-02-24T15:05:21Z" name="beforeClass" finished-at="2024-02-24T15:05:29Z" duration-ms="8438" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="TC_01_openForm()[pri:0, instance:testnextsp.updateProductTest@2145b572]" started-at="2024-02-24T15:05:29Z" name="TC_01_openForm" finished-at="2024-02-24T15:05:29Z" duration-ms="80" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_openForm -->
        <test-method signature="TC_02_checkProductName()[pri:0, instance:testnextsp.updateProductTest@2145b572]" started-at="2024-02-24T15:05:29Z" name="TC_02_checkProductName" finished-at="2024-02-24T15:05:35Z" duration-ms="6179" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Test case update Product Name] but found [Test case update Product ...]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Test case update Product Name] but found [Test case update Product ...]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testnextsp.updateProductTest.TC_02_checkProductName(updateProductTest.java:83)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_02_checkProductName -->
        <test-method signature="TC_03_checkPrice()[pri:0, instance:testnextsp.updateProductTest@2145b572]" started-at="2024-02-24T15:05:35Z" name="TC_03_checkPrice" finished-at="2024-02-24T15:05:42Z" duration-ms="6203" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_03_checkPrice -->
        <test-method signature="TC_04_checkOldPrice()[pri:0, instance:testnextsp.updateProductTest@2145b572]" started-at="2024-02-24T15:05:42Z" name="TC_04_checkOldPrice" finished-at="2024-02-24T15:05:48Z" duration-ms="6197" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_04_checkOldPrice -->
        <test-method signature="TC_05_checkBrand()[pri:0, instance:testnextsp.updateProductTest@2145b572]" started-at="2024-02-24T15:05:48Z" name="TC_05_checkBrand" finished-at="2024-02-24T15:05:52Z" duration-ms="4181" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_05_checkBrand -->
        <test-method signature="TC_06_checkCategory()[pri:0, instance:testnextsp.updateProductTest@2145b572]" started-at="2024-02-24T15:05:52Z" name="TC_06_checkCategory" finished-at="2024-02-24T15:05:56Z" duration-ms="4155" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_06_checkCategory -->
        <test-method signature="TC_07_checkDescription()[pri:0, instance:testnextsp.updateProductTest@2145b572]" started-at="2024-02-24T15:05:56Z" name="TC_07_checkDescription" finished-at="2024-02-24T15:06:02Z" duration-ms="6199" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Test case update description] but found [Test case updat...]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Test case update description] but found [Test case updat...]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testnextsp.updateProductTest.TC_07_checkDescription(updateProductTest.java:201)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_07_checkDescription -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:testnextsp.updateProductTest@2145b572]" started-at="2024-02-24T15:06:02Z" name="afterClass" finished-at="2024-02-24T15:06:02Z" duration-ms="156" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- testnextsp.updateProductTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
